# GET https://jsonplaceholder.typicode.com/users

# ###

POST http://localhost:5100/HV/diner/dCreate
Content-Type: application/json

{
 "fullname": "timothy Avell",
 "username":"timothy",
 "password":"tim",
 "contact":"hell",
 "address":"hell",
 "email": "timothy.avell.olatunde@gmail.com"
}
###
PATCH  http://localhost:5100/HV/diner/dActivation
Content-Type: application/json

{
 "code":"29504",
 "email": "timothy.avell.olatune@gmail.com",
 "id": "IZMVTGkhry5+zexQciPCdGVJO+k02eYY7OH9Slk74157A4bDegSgxLYOyVgBVOgyTh3PKrJptKoH5gM9Djy9gvAjYBJQ8Ph1dQ+llXiLDSd66TJDJ+Sw8f/O4SjNb3MrJl86vcKu6wU9oS1SAu2UuTkSckR5ZwxRhyk2GExmNXQ="
}

###
POST http://localhost:5100/HV/admin/aLogin
Content-Type: application/json

{
 "username": "timothy",
 "email": "timothy.avell.olatune@gmail.com",
 "password": "timm"
}

###
////reset password link
POST http://localhost:5100/HV/chef/cRecovery
Content-Type: application/json

{
 "email": "timothy.avell.olatune@gmail.com"
}
###
GET http://localhost:5100/HV/diner/dReset?u=Yja30uUAwHmEoP4ULHizZimnd5EuPoLdFhsGSgC3Z1XmmDcsOJN2bF2I2cOea0CfbgEw8ZR4W+xrWl+ilNlQ5sW9VnIFGEigzOElVZSykydSi8mMltvhyR2QqaFrNtNTBEuwgVTakmjgjHVlAd/ZN0bA0EFnZ71Rks6dujrxDFU=&t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IllqYTMwdVVBd0htRW9QNFVMSGl6WmltbmQ1RXVQb0xkRmhzR1NnQzNaMVhtbURjc09KTjJiRjJJMmNPZWEwQ2ZiZ0V3OFpSNFcreHJXbCtpbE5sUTVzVzlWbklGR0VpZ3pPRWxWWlN5a3lkU2k4bU1sdHZoeVIyUXFhRnJOdE5UQkV1d2dWVGFrbWpnakhWbEFkL1pOMGJBMEVGblo3MVJrczZkdWpyeERGVT0iLCJpYXQiOjE3MDY1MjU3NTksImV4cCI6MTcwNjUyNjY1OX0.85WQIbyT69f2HwcozLVDpvGmNUSaqfY7sWitoCS25oQ


###